### ISSUE TITLE
这段代码的remainNum是空，才插入。插入的总是一个空。是不是有问题？

### ISSUE THREAD

**Issue by 522263718** [yzxie/eshop#1]
boolean lock = redisLock.tryLock(lockKey, lockValue, 10);
                        if (lock) {
                            // double check检查
                            remainNum = getSecKillNum(productId);
                            if (remainNum == null) {
                                // Redis单线程特性，
                                // 此次会在后面的"递减"之前执行，
                                // 如两个实例同时执行了tryLock方法，获取分布式锁失败的实例会执行到execute部分，不过也是在此操作之后的，
                                // 故可以读取到此处的设值
                                setSecKillNum(productId, remainNum);
                            }
                        }

这段代码的remainNum是空，才插入。插入的总是一个空。是不是有问题？

**Comment by yzxie** [comment]
感谢提醒，确实存在问题，已经修改~

licong <notifications@github.com> 于2020年3月27日周五 下午5:37写道：
